services:
  - type: web
    name: portfolio
    env: static
    buildDir: .
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 